name: Go build and post tweet

on:
  workflow_dispatch:
  schedule:
    # at 09:00 hrs everyday
    - cron: '0 8 * * *'

jobs:

  build:
    runs-on: ubuntu-latest
    environment: PROD
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build

    - name: Test
      run: go test -v ./...
    
    - name: Post Tweets
      run: ./emvolioGR
      env:
          CI: true
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          GOV_DATA_TOKEN: ${{ secrets.GOV_DATA_TOKEN }}
