name: "Snyk Golang"
on:
  push:
  workflow_dispatch:
jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Snyk to check Golang file for issues
      continue-on-error: true
      uses: snyk/actions/golang@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        file: .
    - uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: snyk.sarif
