name: "Snyk Golang"
on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:
jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Snyk to check Golang file for issues
      continue-on-error: true
      uses: snyk/actions/golang@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        file: .
        args: --sarif-file-output=snyk.sarif
    - uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: snyk.sarif
